### ISSUE TITLE
How to build releases version from source code?

### ISSUE THREAD

**Issue by Panxuefeng-loongson** [dacapobench/dacapobench#249]
I would like to build a release dacapo-23.11-chopin.zip with source code. I build based on commmit fd292e92f8c40495a6ca05ff3b8a77c6c4265606， the corresponding tag is v23.11-chopin. I refer to this [documentation](https://github.com/dacapobench/dacapobench?tab=readme-ov-file#building) and build using the ant command. The jar package name is dacapo-evaluation-git-fd292e92.jar， seems a bit different from the community posted jar package name dacapo-23.11-chopin.jar.  What command to use to build out dacapo-23.11-chopin.jar correctly?

**Comment by steveblackburn** [comment]
What you see is correct.

When building from sources, you will get a jar which is named according to the git hash from which you built.  If you want to use the released build (and be certain you have the correct build) please download the release zip.

The reason for this is to maintain integrity of the suite.   If you build and change nothing, then you could just use the provided release zip.  On the other hand, if you build and change something, it is very important that you do _not_ refer to it by the name of the release, since it now differs from the release.

I hope this explanation makes sense.
